
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const QTY_TO_CART_REQUEST = "QTY_TO_CART_REQUEST";
export const QTY_TO_CART_SUCCESS = "QTY_TO_CART_SUCCESS";
export const QTY_TO_CART_FAILED = "QTY_TO_CART_FAILED";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILED = "REMOVE_FROM_CART_FAILED";