


export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";

export const VIEW_ORDER_REQUEST = "VIEW_ORDER_REQUEST";
export const VIEW_ORDER_SUCCESS = "VIEW_ORDER_SUCCESS";
export const VIEW_ORDER_FAILED = "VIEW_ORDER_FAILED";

export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAILED = "ADMIN_ORDERS_FAILED";