

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";


export const CATEGORIE_SELECTED_REQUEST = "CATEGORIE_SELECTED_REQUEST";
export const CATEGORIE_SELECTED_SUCCESS = "CATEGORIE_SELECTED_SUCCESS";
export const CATEGORIE_SELECTED_FAILED = "CATEGORIE_SELECTED_FAILED";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS"

