

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_FILTER_AND_SORT_PRODUCTS_REQUEST = "GET_FILTER_AND_SORT_PRODUCTS_REQUEST";
export const GET_FILTER_AND_SORT_PRODUCTS_SUCCESS = "GET_FILTER_AND_SORT_PRODUCTS_SUCCESS";
export const GET_FILTER_AND_SORT_PRODUCTS_FAILED = "GET_FILTER_AND_SORT_PRODUCTS_FAILED";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const CATEGORIE_SELECTED_REQUEST = "CATEGORIE_SELECTED_REQUEST";
export const CATEGORIE_SELECTED_SUCCESS = "CATEGORIE_SELECTED_SUCCESS";
export const CATEGORIE_SELECTED_FAILED = "CATEGORIE_SELECTED_FAILED";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS"

export const CLEAR_ERROR = "CLEAR_ERROR";

